version: '3.0'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: checkedin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3307:3306'

  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025' # mailhog ui